### PR TITLE
Dev 04 29

### PR DESCRIPTION
**Pull request by JKasakyan**
These will definitely require running both pip install -r requirements.txt and python manage.py migrate after pulling.

### CODE REVIEW

**Comment by ian-s-mcb** [comment]
It seems like you forgot to delete a method in `models.py`.

There are two methods that look identical, but it only one of them is appears to get called:
- `validate_vote_end`
- `validate_vote_time`

**Comment by ian-s-mcb** [comment]
@JKasakyan You probably knew this, but I thought it was worth mentioning that at the moment, none of your templates link to `create_suggestion()` view. That means you have to point your browser to the full URL to create a suggestion.

This is fine because, as of now, we don't have a `league_detail()` view.

**Comment by JKasakyan** [comment]
To the first point:
You're right that validate_vote_end is a leftover from a previous migration. Unfortunately, when I try to delete it, I get errors when I run makemigrations and migrate. I believe it tries to recreate all the migrations each time, and I get an error on an earlier migration that expects that method to exist. There has to be some way around it, but I wasn't able to figure it out.

And yup, currently you have to manually enter the URL to get to the create suggestion page. There is also a problem with the form, where it serves regular CharFields as the input fields for the vote start and vote end times (default behavior for the DateTimeField). I looked into using the input fields used in the admin interface which allow you to select from a calendar, but people recommend not using it because it requires a hacky solution. The recommended method is something like [https://github.com/asaglimbeni/django-datetime-widget](url), but I think this should be handled later on. I'll open an issue for it.

**Comment by ian-s-mcb** [comment]
Thanks for the migration explanation. Have you considered squashing the problematic migration? I doubt we need to hold onto many migrations.

Good call about the DataTimeField. Opening an issue for it makes sense.

**Comment by JKasakyan** [comment]
Good call on squash migrations, that did the trick. I also added league detail and league list urls, views, and templates.

**Comment by allenkim** [comment]
It looks like it's all working. Only bug (if it is a bug) that I noticed was that the admin from createsuperuser can't make leagues through the website since the admin does not have an associated SH_User. Should the admin have an associated SH_User? If not, I think this is good as is.

**Comment by allenkim** [comment]
We also need to add a link to create another suggestion after one has been made.

**Pull request merged**
